###############################################
# Script name..: Fractal dimension calculator
# Created on...: Not available
# Author.......: Paulo Haddad
# Purpose......: Calculate fractal dimensions obtained from the Moving box-counting script (moving_box_counting.py)
# Use..........: To use this script, open it in R or RStudio and simply click Run
# Requirements.: dplyr
# History......: Not available
###############################################
# Main input: a tab-separated file manually exported from the attribute table of the shapefile generated by the script moving_box_counting.py
# An example of the main columns on the tsv file exported from the attribute table:
#   Id  box_size  boxcount
#    1  20000     1
#    1  10000     4
#    1  5000      12
#    1  2500      27
#    1  1250      59
# Main output: a tab-separated file with box Id (the same generated by the moving_box_counting), its corresponding fractal dimension and its r-squared score
# An example of the output is:
#  "box_id" "fractal_dimension" "r_squared"
#   1        1,45201736008872    0,983716341654967
#   2        1,45237610234571    0,981388905450741
#   3        1,44731349503871    0,981879015478655
# The box_id column allows these results to be joined back to the shapefile outputed by the moving_box_counting.py script
# How does this script work?
# For each point in the input table - identified by its Id - this script will perform a linear regression between box size and counts
# The linear regression will allow to find that point's fractal dimension and its r-squared score
###############################################

library(dplyr)

# Ask an input file from the user
input <- file.choose()
dados <- read.delim2(file = input)

# Remove empty boxes (since log(10) cannot be calculated).
# It is important to note that if the largest box has a 0 count, then all smaller boxes will have 0 count.
# The opposite is also true (if count is 1 for the largest box, then all boxes will have at least 1 count)
val_dados <- dados[dados$boxcount != 0,]
box_id <- integer()
fractal_dimension <- double()
r_squared <- double()
boxes <- unique(val_dados$Id)

for (box in boxes){
    box_id <- append(box_id, box)
    regr_line <- lm(log10(boxcount) ~ log10(box_size), data = val_dados[val_dados$Id == box,])
    fractal_dimension <- append(fractal_dimension, regr_line$coefficients[2] * -1)
    r_squared <- append(r_squared, summary.lm(regr_line)$r.squared)
}

frac_dim <- data.frame(box_id, fractal_dimension, r_squared)
print(frac_dim)

# Ask an output file name from the user. Defaults to saving in the same directory of this script
output <- readline(prompt = "Digite o nome do arquivo de saida: ")
write.table(frac_dim, file = output, dec = ',', row.names = FALSE, col.names = TRUE)
